apiVersion: v1
kind: Service
metadata:
  name: demo-nodejs-web
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: demo-nodejs-web
